steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/tech-rnd-project/hello-world:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/tech-rnd-project/hello-world:latest"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gcr.io/tech-rnd-project/hello-world:latest
  - --image=gcr.io/tech-rnd-project/hello-world:latest
  - --location=us-central1-a
  - --cluster=cluster-1
